### ISSUE TITLE
Fatal error: Allowed memory exhausted

### ISSUE THREAD

**Issue by mudrd8mz** [sheesania/moodle-tool_genmobilecss#1]
After pressing the button to download the latest upstream CSS, I got error:

![image](https://user-images.githubusercontent.com/85831/94405093-593bfa80-0170-11eb-83b6-b3af4920afeb.png)

**Comment by sheesania** [comment]
More info in the Moodle plugin approval issue: https://tracker.moodle.org/browse/CONTRIB-8224 Fixed in f30a98a by temporarily raising the memory limit while parsing CSS.
